spring.application.name=croussards_web


server.port=9008

logging.level.root=INFO
logging.level.fr.univ_poitiers=INFO
logging.level.org.springframework.boot.web.embedded.tomcat=INFO

fr.univ_poitiers.croussardsweb.apiUrl=http://localhost:9007